name: "Select Node.js Package Manager"
description: "Selects a package manager to use by running resolution logic"

inputs:
  package-manager:
    description: "Specifies which package manager to use"
    required: false
    default: ""
    type: string

outputs:
  pkg-bin:
    description: "The package manager binary name"
    value: ${{ steps.determine-package-manager.outputs.pkg-bin }}
  install-command:
    description: "A command that can be used to install Node.js modules in CI mode"
    value: ${{ steps.determine-package-manager.outputs.install-command }}

runs:
  using: composite
  steps:
    - name: Determine which package manager to use
      id: determine-package-manager
      shell: bash
      run: |
        # Try to infer which package manager currently in use if not specified
        NODEJS_PACKAGE_MANAGER="${{ inputs.package-manager }}"
        if [[ "${NODEJS_PACKAGE_MANAGER}" == "" ]]; then
          if [[ -f "yarn.lock" ]]; then
            if [[ -d ".yarn/" ]]; then
              NODEJS_PACKAGE_MANAGER="yarn"
            else
              NODEJS_PACKAGE_MANAGER="yarn-legacy"
            fi
          elif [[ -f "pnpm-lock.yaml" ]]; then
            NODEJS_PACKAGE_MANAGER="pnpm"
          else
            NODEJS_PACKAGE_MANAGER="npm"
          fi
        fi
        # Prepare outputs
        case $NODEJS_PACKAGE_MANAGER in
          npm)
            PKG_BIN="npm"
            INSTALL_CMD="npm ci"
            ;;
          yarn)
            PKG_BIN="yarn"
            INSTALL_CMD="yarn install --immutable"
            ;;
          yarn-legacy)
            PKG_BIN="yarn"
            INSTALL_CMD="yarn install --frozen-lockfile"
            ;;
          pnpm)
            PKG_BIN="pnpm"
            INSTALL_CMD="pnpm install --frozen-lockfile"
            ;;
          *)
            echo "Unknown package manager type"
            exit 1
            ;;
        esac
        # Print outputs
        echo "Using package manager: ${PKG_BIN}"
        echo "pkg-bin=${PKG_BIN}" >> $GITHUB_OUTPUT
        echo "Using install command: ${INSTALL_CMD}"
        echo "install-command=${INSTALL_CMD}" >> $GITHUB_OUTPUT
