name: "Multimodule Releaser"
description: "Releases packages in a multimodule repository"
inputs:
  module:
    description: "배포하고자 하는 모듈 명"
    required: true
  bump:
    description: "next tag에서 SemVer 어떤 부분(major, minor, patch)를 올릴지 결정"
    default: "patch"
    required: false
  divider:
    description: "Tag의 Prefix와 Version 사이에 들어갈 구분자"
    default: "-"
    required: false
  workflow-file:
    description: "실제 배포가 진행되는 workflow 파일 경로"
    default: ""
    required: false
  workflow-inputs:
    description: "실제 배포가 진행되는 workflow 파일에 전달할 값 (json 형태)"
    default: ""
    required: false
  latest:
    description: "make the release latest"
    default: "false"
    required: false
  date-suffix:
    description: "Tag의 Version 뒤에 날짜를 붙일지 여부"
    default: "false"
    required: false
  
runs:
  using: composite
  steps:
    - name: Generate Changelog
      id: changelog
      uses: bucketplace/ci/.github/actions/multimodule-changelog@latest
      with:
        module: '${{ inputs.module }}'
        bump: '${{ inputs.bump }}'
        divider: '${{ inputs.divider }}'
    - name: Release And Dispatch
      uses: bucketplace/ci/.github/actions/release-and-dispatch@latest
      with:
        next-tag: '${{ steps.changelog.outputs.next-tag }}'
        changelog: '${{ steps.changelog.outputs.changelog }}'
        workflow-file: '${{ inputs.workflow-file }}'
        workflow-inputs: '${{ inputs.workflow-inputs }}'
        latest: '${{ inputs.latest }}'
        date-suffix: '${{ inputs.date-suffix }}'
