name: "Multimodule Releaser"
description: "Releases packages in a multimodule repository"
inputs:
  module:
    description: "ë°°í¬í•˜ê³ ìž í•˜ëŠ” ëª¨ë“ˆ ëª…"
    required: true
  workflow-file:
    description: "ì‹¤ì œ ë°°í¬ê°€ ì§„í–‰ë˜ëŠ” workflow íŒŒì¼ ê²½ë¡œ"
    default: ""
    required: false
  workflow-inputs:
    description: "ì‹¤ì œ ë°°í¬ê°€ ì§„í–‰ë˜ëŠ” workflow íŒŒì¼ì— ì „ë‹¬í•  ê°’ (json í˜•íƒœ)"
    default: ""
    required: false
  bump:
    description: "next tagì—ì„œ SemVer ì–´ë–¤ ë¶€ë¶„(major, minor, patch)ë¥¼ ì˜¬ë¦´ì§€ ê²°ì •"
    default: "patch"
    required: false
  latest:
    description: "make the release latest"
    default: "false"
    required: false
  divider:
    description: "Tagì˜ Prefixì™€ Version ì‚¬ì´ì— ë“¤ì–´ê°ˆ êµ¬ë¶„ìž"
    default: "-"
    required: false
  date-suffix:
    description: "Tagì˜ Version ë’¤ì— ë‚ ì§œë¥¼ ë¶™ì¼ì§€ ì—¬ë¶€"
    default: "false"
    required: false

outputs:
  released:
    description: "ë°°í¬ëœ íƒœê·¸ ëª…"
    value: ${{ steps.generate-next-tag.outputs.tag }}
  
runs:
  using: composite
  steps:
    - name: Generate Next Tag
      id: get-tag
      uses: bucketplace/ci/.github/actions/release-tag-finder@latest
      with:
        prefix: '${{ inputs.module }}${{ inputs.divider }}'
        bump: '${{ github.event.inputs.bump }}'
    - name: Build Changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v3
      with:
        configurationJson: |
          {
            "categories": [
              {
                "title": "## ðŸš€ Features",
                "labels": ["feature", "module/${{ inputs.module }}"],
                "exhaustive": true
              },
              {
                "title": "## ðŸ› Bug Fixes",
                "labels": ["bugfix", "module/${{ inputs.module }}"],
                "exhaustive": true
              },
              {
                "title": "## ðŸ§ª Tests",
                "labels": ["test", "module/${{ inputs.module }}"],
                "exhaustive": true
              },
              {
                "title": "## ðŸ“¦ Dependencies",
                "labels": ["dependencies", "module/${{ inputs.module }}"],
                "exhaustive": true
              },
              {
                "title": "## ðŸ’¬ Others",
                "labels": ["module/${{ inputs.module }}"],
                "exclude_labels": ["feature", "bugfix", "test", "dependencies"]
              }
            ],
            "template": "#{{CHANGELOG}}",
            "pr_template": "- #{{TITLE}}\n   - PR: ##{{NUMBER}}",
            "empty_template": "- no changes"
          }
        fromTag: ${{ steps.get-tag.outputs.current-tag }}
        toTag: ${{ github.ref }}
    - name: Get Date Suffix
      id: get-date-suffix
      run: |
        if [[ "${{ inputs.date-suffix }}" == "true" ]]; then
          echo "suffix=@$(date +'%y%m%d')" >> "$GITHUB_OUTPUT"
        else 
          echo "suffix=" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
    - name: "Create Release for Version (${{ steps.get-tag.outputs.next-version }})"
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.get-tag.outputs.next-tag }}
        name: ${{ steps.get-tag.outputs.next-tag }}${{ steps.get-date-suffix.outputs.suffix }}
        makeLatest: ${{ inputs.latest }}
        body: ${{ steps.changelog.outputs.changelog }}
    - name: trigger workflow with versions
      if: ${{ inputs.workflow-file != '' }}
      uses: benc-uk/workflow-dispatch@v1
      id: trigger-workflow
      with:
        workflow: ${{ inputs.workflow-file }}
        ref: "refs/tags/${{ steps.get-tag.outputs.next-tag }}"
        inputs: ${{ inputs.workflow-inputs }}
    - name: print changelog 
      run: |
        cat  <<EOF >> $GITHUB_STEP_SUMMARY
        # Process
          release if triggered: [${{ steps.get-tag.outputs.next-tag }}](https://github.com/${{ github.repository }}/actions/workflows/${{ inputs.workflow-file }})
        # Changelog
        ${{ steps.changelog.outputs.changelog }}
        EOF
      shell: bash
