name: "Multimodule Releaser"
description: "Releases packages in a multimodule repository"
inputs:
  module:
    description: "ë°°í¬í•˜ê³ ìž í•˜ëŠ” ëª¨ë“ˆ ëª…"
    required: true
  workflow-file:
    description: "ì‹¤ì œ ë°°í¬ê°€ ì§„í–‰ë˜ëŠ” workflow íŒŒì¼ ê²½ë¡œ"
    default: ""
    required: false
  workflow-inputs:
    description: "ì‹¤ì œ ë°°í¬ê°€ ì§„í–‰ë˜ëŠ” workflow íŒŒì¼ì— ì „ë‹¬í•  ê°’ (json í˜•íƒœ)"
    default: ""
    required: false
  bump:
    description: "next tagì—ì„œ SemVer ì–´ë–¤ ë¶€ë¶„(major, minor, patch)ë¥¼ ì˜¬ë¦´ì§€ ê²°ì •"
    default: "patch"
    required: false
  version-prefix:
    description: "version with prefix (ex. v for module-v1.2.0)"
    default: ""
    required: false
  latest:
    description: "make the release latest"
    default: "false"
    required: false

outputs:
  released:
    description: "ë°°í¬ëœ íƒœê·¸ ëª…"
    value: ${{ steps.generate-next-tag.outputs.tag }}
  
runs:
  using: composite
  steps:
    - name: Generate Next Tag
      id: get-tag
      uses: bucketplace/ci/.github/actions/release-tag-finder@latest
      with:
        prefix: '${{ inputs.module }}-${{ inputs.version-prefix }}'
        bump: '${{ github.event.inputs.bump }}'
    - uses: rickstaa/action-create-tag@v1
      with:
        tag: "${{ steps.get-tag.outputs.next-tag }}"
    - name: Build Changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v3
      with:
        configurationJson: |
          {
            "categories": [
              {
                "title": "## ðŸš€ Features",
                "labels": ["feature", "module/${{ inputs.module }}"],
                "exhaustive": true
              },
              {
                "title": "## ðŸ› Bug Fixes",
                "labels": ["bugfix", "module/${{ inputs.module }}"],
                "exhaustive": true
              },
              {
                "title": "## ðŸ§ª Tests",
                "labels": ["test", "module/${{ inputs.module }}"],
                "exhaustive": true
              },
              {
                "title": "## ðŸ“¦ Dependencies",
                "labels": ["dependencies", "module/${{ inputs.module }}"],
                "exhaustive": true
              },
              {
                "title": "## ðŸ’¬ Others",
                "labels": ["module/${{ inputs.module }}"],
                "exclude_labels": ["feature", "bugfix", "test", "dependencies"]
              }
            ],
            "template": "#{{CHANGELOG}}",
            "pr_template": "- #{{TITLE}}\n   - PR: ##{{NUMBER}}",
            "empty_template": "- no changes"
          }
        fromTag: ${{ steps.get-tag.outputs.current-tag }}
        toTag: ${{ steps.get-tag.outputs.next-tag }}
    - name: print changelog 
      run: |
        echo ${{ steps.changelog.outputs.changelog }} >> $GITHUB_STEP_SUMMARY
      shell: bash
    - name: "Create Release for Version (${{ steps.get-tag.outputs.next-version }})"
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.get-tag.outputs.next-tag }}
        name: ${{ steps.get-tag.outputs.next-tag }}
        makeLatest: ${{ inputs.latest }}
        body: ${{ steps.changelog.outputs.changelog }}
        allowUpdates: true
    - name: trigger workflow with versions
      if: ${{ inputs.worflow-file != '' }}
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: ${{ inputs.worflow-file }}
        ref: "refs/tags/${{ inputs.version }}"
        inputs: ${{ inputs.workflow-inputs }}
