name: "Pre-Process Build Cache"
description: "Pre-Process Build Cache"
inputs:
  app-name:
    description: "앱 이름"
    required: true
  cache-path:
    description: "캐시 경로"
    required: false
    default: "/var/cache"
  
runs:
  using: composite
  steps:
    - name: Pre-Process Build Cache
      id: pre-cache
      shell: bash
      run: |
        # setup cache dirs
        SHARED_CACHE_DIR="${{ inputs.cache-path }}/${{ inputs.app-name }}"
        LOCAL_CACHE_DIR="/home/runner/cache"
        
        # For Gradle
        rm -rf ${LOCAL_CACHE_DIR}/gradle
        mkdir -p ${LOCAL_CACHE_DIR}/gradle/caches
        mkdir -p "${SHARED_CACHE_DIR}/gradle/wrapper"
        cp -a "${SHARED_CACHE_DIR}/gradle/wrapper" "${LOCAL_CACHE_DIR}/gradle/"
        echo "Loading gradle wrapper cache has completed."
        echo "GRADLE_USER_HOME=${LOCAL_CACHE_DIR}/gradle" >> $GITHUB_ENV
        echo "GRADLE_RO_DEP_CACHE=${SHARED_CACHE_DIR}/gradle/caches" >> $GITHUB_ENV
        echo "${{ github.run_id }}" > "${LOCAL_CACHE_DIR}/gradle/caches/run_info"
        echo "Setting up gradle environment variables has completed. - GRADLE_USER_HOME: ${GRADLE_USER_HOME}, GRADLE_RO_DEP_CACHE: ${GRADLE_RO_DEP_CACHE}"
