name: "Multimodule Releaser"
description: "Releases packages in a multimodule repository"
inputs:
  module:
    description: "배포하고자 하는 모듈 명"
    required: true
  bump:
    description: "next tag에서 SemVer 어떤 부분(major, minor, patch)를 올릴지 결정"
    default: "patch"
    required: false
  divider:
    description: "Tag의 Prefix와 Version 사이에 들어갈 구분자"
    default: "-"
    required: false
outputs:
  next-tag:
    description: "생성될 태그 명"
    value: ${{ steps.get-tag.outputs.tag }}
  changelog:
    description: "생성될 태그에 대한 Changelog"
    value: ${{ steps.changelog.outputs.changelog }}
  
runs:
  using: composite
  steps:
    - name: Get Tags
      id: get-tag
      uses: bucketplace/ci/.github/actions/release-tag-finder@latest
      with:
        prefix: '${{ inputs.module }}${{ inputs.divider }}'
        bump: '${{ github.event.inputs.bump }}'
    - name: Build Changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v3
      with:
        configurationJson: |
          {
            "categories": [
              {
                "title": "## 🚀 Features",
                "labels": ["feature", "module/${{ inputs.module }}"],
                "exhaustive": true
              },
              {
                "title": "## 🐛 Bug Fixes",
                "labels": ["bugfix", "module/${{ inputs.module }}"],
                "exhaustive": true
              },
              {
                "title": "## 🧪 Tests",
                "labels": ["test", "module/${{ inputs.module }}"],
                "exhaustive": true
              },
              {
                "title": "## 📦 Dependencies",
                "labels": ["dependencies", "module/${{ inputs.module }}"],
                "exhaustive": true
              },
              {
                "title": "## 💬 Others",
                "labels": ["module/${{ inputs.module }}"],
                "exclude_labels": ["feature", "bugfix", "test", "dependencies"]
              }
            ],
            "template": "#{{CHANGELOG}}",
            "pr_template": "- #{{TITLE}} @#{{AUTHOR}}\n   - PR: ##{{NUMBER}}",
            "empty_template": "- no changes"
          }
        fromTag: ${{ steps.get-tag.outputs.current-tag }}
        toTag: ${{ github.ref }}
    - name: print changelog 
      run: |
        cat  <<EOF >> $GITHUB_STEP_SUMMARY
        # Version
        ${{ steps.get-tag.outputs.next-tag }}
        # Changelog
        ${{ steps.changelog.outputs.changelog }}
        EOF
      shell: bash
