name: "Check Go"

on:
  workflow_call:
    inputs:
      app-name:
        description: "sonarqube 프로젝트를 선택을 위한 앱 이름"
        required: true
        type: string
      app-path:
        type: string
        description: "앱 기준 디렉토리"
        required: false
        default: "."
      lint-config:
        type: string
        description: "golangci-lint config 파일 이름"
        required: false
        default: ".golangci.yaml"
      go-version:
        type: string
        description: go 버전
        required: false
      filter-mode:
        type: string
        description: reviewdog 결과 필터링 모드. [added, diff_context, file, nofilter] 중 하나
        default: nofilter # 모든 결과를 보여줌
      sonar-host-url:
        type: string
        description: "sonarqube 호스트 URL"
        required: false
        default: "https://sonarqube.co-workerhou.se"
      sonar-exclusions:
        type: string
        description: "sonarqube 리포트에서 제외 대상 Path 리스트. ','로 구분"
        required: false
        default: "**/*_test.go,**/mock_*.go"
      coverage-threshold:
        type: string
        description: "unit test coverage threshold"
        required: false
        default: "70 70"
      use-ginkgo:
        type: boolean
        description: "테스트를 위해 Ginkgo CLI를 사용할 것인지 여부"
        required: false
        default: true
      use-sonar-report:
        type: boolean
        description: "sonarqube 리포트를 사용할 것인지 여부"
        required: false
        default: true
    secrets:
      SONAR_TOKEN:
        required: false
      BP_DEPLOYER_GITHUB_TOKEN: # if you need private github module access
        required: false
jobs:
  lint:
    name: Lint
    runs-on: [self-hosted, Linux, X64, cache]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Granting private modules access
        env:
          TOKEN: ${{ secrets.BP_DEPLOYER_GITHUB_TOKEN }}
        if: env.TOKEN != null
        run: |
          git config --global url."https://bp-deployer:${TOKEN}@github.com/bucketplace/".insteadOf "https://github.com/bucketplace/"
      - name: Lint
        uses: reviewdog/action-golangci-lint@v2
        env:                                                                    
          GOPROXY: "https://go.co-workerhou.se,https://proxy.golang.org,direct"
          GONOSUMDB: "go.dailyhou.se"
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
          workdir: ${{ inputs.app-path }}
          go_version: ${{ inputs.go-version }}
          go_version_file: ${{ inputs.app-path}}/go.mod
          reporter: ${{ inputs.reporter }}
          filter_mode: ${{ inputs.filter-mode }}
          fail_on_error: true
          golangci_lint_version: v1.52.2 # last update: 2023.03.29
          golangci_lint_flags: |
            --config=${{ inputs.lint-config }} ./...

  test-report:
    name: Test And Report
    runs-on: [self-hosted, Linux, X64, cache]
    steps:
      - name: Report Summary
        run: |
          cat >> "$GITHUB_STEP_SUMMARY" << EOF
          ## Request Information
          | Name | Details |
          | --- | --- |
          | App Name | ${{ inputs.app-name }} |
          | App Path | ${{ inputs.app-path }} |
          | Lint Config Path | ${{ inputs.lint-config}} |
          | Deployed By | @${{ github.actor }} |

          EOF
        shell: bash
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          cache: true
          cache-dependency-path: ${{ inputs.app-path }}/go.sum
          go-version-file: ${{ inputs.app-path }}/go.mod
          go-version: ${{ inputs.go-version }}
      - name: Granting private modules access
        env:
          TOKEN: ${{ secrets.BP_DEPLOYER_GITHUB_TOKEN }}
        if: env.TOKEN != null
        run: |
          git config --global url."https://bp-deployer:${TOKEN}@github.com/bucketplace/".insteadOf "https://github.com/bucketplace/"
      - name: Setup Environment
        run: |
          go env -w GOPROXY=https://go.co-workerhou.se,https://proxy.golang.org,direct && \
          go env -w GONOSUMDB=go.dailyhou.se && \
          go install github.com/axw/gocov/gocov@latest && \
          go install github.com/AlekSi/gocov-xml@latest
      - name: Test with Ginkgo
        if: inputs.use-ginkgo
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH && cd ${{ inputs.app-path }} && \
          && go install github.com/onsi/ginkgo/v2/ginkgo && \
          ginkgo -p --race --trace --cover --coverprofile=coverage.txt ./...
      - name: Test with Go Test
        if: ${{ !inputs.use-ginkgo }}
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH && cd ${{ inputs.app-path }} && \
          go test -v -cover -coverprofile=coverage.txt ./...
      - name: Convert Coverage Format
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH && cd ${{ inputs.app-path }} && \
          gocov convert coverage.txt | gocov-xml > coverage.xml
      - name: Create Coverage Information
        if: always() && github.event_name == 'pull_request'
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "${{ inputs.app-path }}/coverage.xml"
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: file
          thresholds: ${{ inputs.coverage-threshold }}
      - name: SonarQube Config Validation
        if: always() && inputs.use-sonar-report
        id: sonarqube-validation
        shell: bash
        run: |
          if [ ${{ secrets.SONAR_TOKEN == null }}
          then
            echo "SONAR_TOKEN secret is required. SonarQube steps will be skipped." 
            echo "sonarqube-available=false" >> $GITHUB_OUTPUT
          else
            echo "sonarqube-available=true" >> $GITHUB_OUTPUT
      - name: SonarQube Scanner Parameters Config
        if: always() && ${{ steps.sonarqube-validation.outputs.sonarqube-available == "true" }}
        id: sonarqube-params
        uses: philips-software/sonar-scanner-action@v1.5.1
        with:
          projectName: ${{ inputs.app-name }}
          projectKey: ${{ inputs.app-name }}
          token: ${{ secrets.SONAR_TOKEN }}
          url: ${{ inputs.sonar-host-url }}
          enablePullRequestDecoration: true
          isCommunityEdition: false
          organization: bucketplace
          onlyConfig: true
      - name: SonarQube Scan
        if: inputs.use-sonar-report && ${{ steps.sonarqube-validation.outputs.sonarqube-available == "true" }}
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
        with:
          projectBaseDir: ${{ inputs.app-path }}
          args: >
            -Dsonar.go.coverage.reportPaths=coverage.txt
            -Dsonar.exclusions=${{ inputs.sonar-exclusions }}
            ${{ steps.sonarqube-params.outputs.sonarParameters }}
      - name: Add Result To Summary
        if: always() && github.event_name == 'pull_request'
        run: |
          cat code-coverage-results.md >> result.md
          echo "" >> result.md
          echo "---" >> result.md
          echo "#### Sonarqube Report" >> result.md
          echo "See [Sonarqube Report](${{ inputs.sonar-host-url }}/dashboard?id=${{ inputs.app-name }}&pullRequest=${{ github.event.pull_request.number }}) (login required)" >> result.md
          cat result.md >> "$GITHUB_STEP_SUMMARY"

      - name: Add Report To PR
        if: always() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: result.md
