name: "Check Node.js"

on:
  workflow_call:
    inputs:
      app-path:
        description: "Specifies a base directory to run the task from"
        required: false
        default: "."
        type: string
      nodejs-version:
        description: "Specifies which Node.js version to use"
        required: false
        default: "18"
        type: string
      package-manager:
        description: "Specifies which package manager to use"
        required: false
        default: ""
        type: string
      test-command:
        description: "Specifies a test command that will be passed to the package manager"
        required: false
        default: "test"
        type: string
      test-command-args:
        description: "Specifies an optional arguments to the test command"
        required: false
        default: ""
        type: string

env:
  NODE_ENV: development # This must always be set. Otherwise, required dependencies to run test will not be installed or inconsistency happens.
  CI: true

jobs:
  run-test:
    name: Run Node.js test
    runs-on: [self-hosted, Linux, X64, cache, node-18]
    defaults:
      run:
        working-directory: ${{ inputs.app-path }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: bucketplace/ci/.github/actions/setup-nodejs@latest
        with:
          nodejs-version: ${{ inputs.nodejs-version }}
        env:
          NPM_TOKEN: ${{ secrets.NEXUS_NPM_TOKEN }}
      - name: Determine package manager
        id: pkg-manager
        uses: bucketplace/ci/.github/actions/select-nodejs-pkg-manager@latest
        with:
          app-path: ${{ inputs.app-path }}
          package-manager: ${{ inputs.package-manager }}
      - name: Install dependencies
        run: ${{ steps.pkg-manager.outputs.install-cmd }}
      - name: Run test
        run: ${{ steps.pkg-manager.outputs.run-cmd }} ${{ inputs.test-command }} ${{ inputs.test-command-args }}
