name: "Check Protobuf Lint"

on:
  workflow_call:

jobs:
  protolint:
    name: protolint
    runs-on: [self-hosted, Linux, X64, cache]
    steps:
      - uses: actions/checkout@v4
      - uses: yoheimuta/action-protolint@v1
        with:
          protolint_flags: -config_path=.protolint.yaml
