name: "Check Protobuf Lint"

on:
  workflow_call:

jobs:
  protolint:
    name: protolint
    runs-on: [self-hosted, Linux, X64, cache]
    permissions: write-all
    steps:
      - uses: yoheimuta/action-protolint@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          protolint_flags: -config_path=.protolint.yaml .
          fail_on_error: true
          level: error
