name: "Check Protobuf Lint"

on:
  workflow_call:
    inputs:
      plugin:
        type: string
        description: "Proto lint plugin path"
        required: false
        default: "../../example/plugin_example"
      lint-config:
        type: string
        description: "Proto lint config file path"
        required: false
        default: ".protolint.yaml"

jobs:
  protolint:
    name: protolint
    runs-on: [self-hosted, Linux, X64, cache]
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - name: Initialize Go modules
        run: |
          go mod init && \
          go env -w GOPROXY=https://go.co-workerhou.se,https://proxy.golang.org,direct && \
          go env -w GONOSUMDB=go.dailyhou.se
      - name: Create plugin
        run: go build -o myPlugin example/main.go
      - name: Check protolint lint w/ plugin
        uses: yoheimuta/action-protolint@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          protolint_flags: -plugin=./myPlugin *
          fail_on_error: true
          level: error
      - name: Check protolint lint w/ config
        uses: yoheimuta/action-protolint@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          protolint_flags: -config_path=${{ inputs.lint-config }} *
          fail_on_error: true
          level: error
      - name: Check protolint lint w/ plugin and config
        uses: yoheimuta/action-protolint@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          protolint_flags: -plugin=${{ inputs.plugin }} -config_path=${{ inputs.lint-config }} .
          fail_on_error: true
          level: error
