name: "Check Protobuf Lint"

on:
  workflow_call:
    inputs:
      app-path:
        type: string
        description: "The path to the app directory"
        required: false
        default: "."

jobs:
  protolint:
    name: protolint
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check if .protolint.yaml exists
        run: |
          if [ -f target/.protolint.yaml ]; then
            echo "File exists."
          else
            echo "File does not exist."
            exit 1
          fi
      - name: Copy Protolint Config
        working-directory: $GITHUB_WORKSPACE
        run: cp target/.protolint.yaml .protolint.yaml
      - uses: yoheimuta/action-protolint@v1.2.0
        with:
          protolint_flags: -config_path=.protolint.yaml .
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          level: error
