name: "Check Protobuf Lint"

on:
  workflow_call:

jobs:
  protolint:
    name: protolint
    runs-on: [ self-hosted, Linux, X64, cache ]
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: yoheimuta/action-protolint@v1
        with:
          protolint_flags: -plugin=../../example/plugin_example -config_path=.protolint.yaml ${{ inputs.app-path }}/.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          level: error
