name: "Check Protobuf Lint"

on:
  workflow_call:

jobs:
  protolint:
    name: protolint
    runs-on: [self-hosted, Linux, X64, cache]
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          repository: bucketplace/ci
          path:  ci
      - name: Print the config file
        run: |
          cat ci/.github/workflows/.protolint.yaml
      - name: Save protolint config as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: protolint-config
          path: ci/.github/workflows/.protolint.yaml
      - uses: yoheimuta/action-protolint@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          protolint_flags: -config_path=ci/.github/workflows/.protolint.yaml .
          fail_on_error: true
          level: error
