name: "Deploy Go Package"

on:
  workflow_call:
    inputs:
      package-name:
        type: string
        description: "배포될 패키지의 앱 이름 (ex. go.dailyhou.se/gohouse/pack)"
        required: true
      package-version:
        type: string
        description: 패키지 배포 버전
        required: false
      package-path:
        type: string
        description: "레포지토리 기준 패키지 루트 디렉토리 디렉토리"
        required: false
        default: "."
      increment-version-segment:
        type: string
        description: 'Increment version of release (major, minor, patch)'
        required: false
        default: 'patch'
      version-prefix:
        type: string
        default: ''
        description: 업데이트를 진행할 버전 e.g) N.N.N, N.N, N, ''
        required: false
      pre-release-version:
        type: string
        default: ''
        description: Pre-Release 버전
        required: false
      go-version:
        type: string
        description: go 버전
        required: false
        default: "1.18"
    secrets:
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
jobs:
  lint:
    name: Deploy
    runs-on: [self-hosted, Linux, X64, cache]
    outputs:
      module-version: ${{ steps.deploy-go-package.outputs.module-version }}
    steps:        
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          cache: true
          cache-dependency-path: ${{ inputs.package-path }}/go.sum
          go-version: ${{ inputs.go-version }}
      - name: Setup Environment
        run: |
          go env -w GOPROXY=https://go.co-workerhou.se,https://proxy.golang.org,direct && \
          go env -w GONOSUMDB=go.co-workerhou.se && \
          go install go.co-workerhou.se/gohouse/pack/cmd/pack@v0.4.1
      - name: Deploy Package
        id: deploy-go-package
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH && \
          pack --module-name="${{ inputs.package-name }}" \
            --module-root-path="${{ inputs.package-path }}" \
            --module-version="${{ inputs.package-version }}" \
            --version-prefix="${{ inputs.version-prefix }}" \
            --pre-release-version="${{ inputs.pre-release-version }}" \
            --increment-version-segment="${{ inputs.increment-version-segment }}" \
            --aws-access-key-id="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            --aws-secret-access-key="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            --github
      - name: Add Summary
        run: |
          cat >> "$GITHUB_STEP_SUMMARY" << EOF
          ## Request Information
          | Name | Details |
          | --- | --- |
          | Package Name | ${{ inputs.package-name }} |
          | Package Version | ${{ steps.deploy-go-package.outputs.module-version }} |
          | Package Version Prefix | ${{ inputs.version-prefix }} |
          | Package Pre Release Version | ${{ inputs.pre-release-version }} |
          | Increment Version Segment | ${{ inputs.increment-version-segment }} |
          | App Path | ${{ inputs.package-path }} |
          | Go Version | ${{ inputs.go-version }} |
          | Deployed By | @${{ github.actor }} |
          EOF
