name: "Release CI Workflows and Actions"

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: 'Increment version of release (major, minor, patch)'
        required: true
        default: 'patch'
        options:
          - 'major'
          - 'minor'
          - 'patch'

jobs:
  changelog:
    runs-on: ubuntu-latest
    outputs: 
      next-tag: ${{ steps.changelog.outputs.next-tag }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    permissions:
      contents: write
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - id: changelog
      uses: bucketplace/ci/.github/actions/multimodule-changelog@latest
      with:
        module: ''
        divider: ''
        bump: ${{ inputs.bump }}
  release:
    needs: changelog
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      actions: write
    steps:
    - uses: actions/checkout@v3
    - id: release
      uses: bucketplace/ci/.github/actions/release-and-dispatch@latest
      with:
        next-tag: '${{ needs.changelog.outputs.next-tag }}'
        changelog: '${{ needs.changelog.outputs.changelog }}'
        latest: true
        date-suffix: true
    - name: Parsing Next SemVer
      uses: madhead/semver-utils@latest
      id: next-version
      with:
        version: ${{ needs.changelog.outputs.next-tag }}
    - name: Update major git tag to HEAD
      uses: rickstaa/action-create-tag@v1
      with:
        tag: "v${{ steps.next-version.outputs.major }}"
        force_push_tag: true
        tag_exists_error: false
        message: "'v${{ steps.next-version.outputs.major }}' release: ${{ needs.changelog.outputs.next-tag }}"
    - name: Update Git tag 'latest' to HEAD
      uses: rickstaa/action-create-tag@v1
      with:
        tag: "latest"
        force_push_tag: true
        tag_exists_error: false
        message: "'latest' release: ${{ needs.changelog.outputs.next-tag }}"
