name: "Release CI Workflows and Actions"

on:
  push:
    branches:
      - main

jobs:
  release-self:
    name: Run release on self
    runs-on: [self-hosted, Linux, X64, no-cache]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Get next version
        uses: reecetech/version-increment@2023.3.1
        id: version
        with:
          scheme: semver
          increment: major
      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          makeLatest: true
          generateReleaseNotes: true
          name: ${{ steps.version.outputs.major-v-version }}
          tag: ${{ steps.version.outputs.major-v-version }}
          token: ${{ github.token }}
      - name: Update Git tag 'latest' to HEAD
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest"
          force_push_tag: true
          tag_exists_error: false
          message: "Latest release: ${{ steps.version.outputs.major-v-version }}"
