name: "Publish Packages"

on:
  workflow_call:
    inputs:
      app-path:
        description: "Specifies a base directory to run the task from"
        required: false
        default: "."
        type: string
      nodejs-version:
        description: "Specifies which Node.js version to use"
        required: false
        default: "18"
        type: string
      package-manager:
        description: "Specifies which package manager to use"
        required: false
        default: ""
        type: string
      build-command:
        description: "Specifies a build command used on package finalizing before publish"
        required: false
        default: "build"
        type: string
    secrets:
      NEXUS_NPM_TOKEN:
        description: "A Nexus NPM token for publishing packages"
        required: true

env:
  CI: true

jobs:
  publish:
    name: Run Changesets publish
    runs-on: [self-hosted, Linux, X64, cache, node-18]
    defaults:
      run:
        working-directory: ${{ inputs.app-path }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: bucketplace/ci/.github/actions/setup-nodejs@latest
        with:
          nodejs-version: ${{ inputs.nodejs-version }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Determine package manager
        id: pkg-manager
        uses: bucketplace/ci/.github/actions/select-nodejs-pkg-manager@latest
        with:
          app-path: ${{ inputs.app-path }}
          package-manager: ${{ inputs.package-manager }}
      - name: Install dependencies
        run: ${{ steps.pkg-manager.outputs.install-cmd }}
      - name: Build packages
        run: ${{ steps.pkg-manager.outputs.run-cmd }} ${{ inputs.build-command }}
        env:
          NODE_ENV: production
      - name: Publish package
        uses: changesets/action@v1
        with:
          publish: ${{ steps.pkg-manager.outputs.exec-cmd }} changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
