name: "Snapshot Packages"

on:
  workflow_call:
    inputs:
      app-path:
        description: "Specifies a base directory to run the task from"
        required: false
        default: '.'
        type: string
      nodejs-version:
        description: "Specifies which Node.js version to use"
        required: false
        default: '16'
        type: string
      package-manager:
        description: "Specifies which package manager to use"
        required: false
        default: ''
        type: string
      build-command:
        description: "Specifies a build command used on package finalizing before publish"
        required: false
        default: 'build'
        type: string
      branch:
        description: "Specifies which branch ref to use on checkout"
        required: false
        default: ${{ github.ref }}
        type: string
      snapshot-tag:
        description: "Specifies a tag name that is used for snapshot release"
        required: false
        default: 'snap'
        type: string
    outputs:
      pkg-version-name-pairs:
        description: "The package metadata with (name, version) pairs in CSV format"
        value: ${{ jobs.snapshot.outputs.pkg-version-name-pairs }}
    secrets:
      NEXUS_NPM_TOKEN:
        description: "A Nexus NPM token for publishing packages"
        required: true

env:
  NODE_ENV: production
  CI: true

jobs:
  snapshot:
    name: Run Changesets snapshot
    runs-on: [self-hosted, Linux, X64, cache, node-16]
    defaults:
      run:
        working-directory: ${{ inputs.app-path }}
    outputs:
      pkg-version-name-pairs: ${{ steps.pkg-name-version-pairs.outputs.message }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Use Node.js ${{ inputs.nodejs-version }}
        run: echo ${{ inputs.nodejs-version }} > .nvmrc && nvm use
      - name: Configure registry
        run: |
          cat <<EOF > "$HOME/.npmrc"
            //nexus.co-workerhou.se/repository/npm-private/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NEXUS_NPM_TOKEN }}
      - name: Determine which package manager to use
        id: pkg-manager
        uses: bucketplace/ci/.github/actions/select-nodejs-pkg-manager@latest
        with:
          package-manager: ${{ inputs.package-manager }}
      - name: Install dependencies
        run: ${{ steps.pkg-manager.outputs.install-cmd }}
      - name: Build packages
        run: ${{ steps.pkg-manager.outputs.run-cmd }} ${{ inputs.build-command }}
      - name: Change version for snapshot
        run: ${{ steps.pkg-manager.outputs.exec-cmd }} changeset version --snapshot ${{ inputs.snapshot-tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Store metadata for released packages
        id: pkg-name-version-pairs
        run: echo "message=$(git ls-files -m | grep package.json | xargs -I{} sh -c "node -e \"const pkg = require('./{}');console.log([pkg.name, pkg.version].join())\"")" >> $GITHUB_OUTPUT
      - name: Publish snapshot
        run: ${{ steps.pkg-manager.outputs.exec-cmd }} changeset publish --tag ${{ inputs.snapshot-tag }} --snapshot --no-git-tag
