name: "Prerelease Packages"

on:
  workflow_call:
    inputs:
      app-path:
        description: "Specifies a base directory to run the task from"
        required: false
        default: "."
        type: string
      nodejs-version:
        description: "Specifies which Node.js version to use"
        required: false
        default: "18"
        type: string
      package-manager:
        description: "Specifies which package manager to use"
        required: false
        default: ""
        type: string
      build-command:
        description: "Specifies a build command used on package finalizing before publish"
        required: false
        default: "build"
        type: string
      prerelease-tag:
        description: "Specifies a tag name that is used for prerelease mode"
        required: false
        default: "pre"
        type: string
    secrets:
      NEXUS_NPM_TOKEN:
        description: "A Nexus NPM token for publishing packages"
        required: true

env:
  NODE_ENV: production
  CI: true

jobs:
  prerelease:
    name: Run Changesets prerelease
    runs-on: [self-hosted, Linux, X64, cache, node-18]
    defaults:
      run:
        working-directory: ${{ inputs.app-path }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ inputs.nodejs-version }}
        run: echo ${{ inputs.nodejs-version }} > .nvmrc && nvm use
      - name: Configure registry
        run: |
          cat <<EOF > "$HOME/.npmrc"
            //nexus.co-workerhou.se/repository/npm-private/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NEXUS_NPM_TOKEN }}
      - name: Determine which package manager to use
        id: pkg-manager
        uses: bucketplace/ci/.github/actions/select-nodejs-pkg-manager@latest
        with:
          package-manager: ${{ inputs.package-manager }}
      - name: Install dependencies
        run: ${{ steps.pkg-manager.outputs.install-cmd }}
      - name: Enter prerelease Mode
        run: ${{ steps.pkg-manager.outputs.exec-cmd }} changeset pre enter ${{ inputs.prerelease-tag }}
      - name: Bump version for prerelease
        run: ${{ steps.pkg-manager.outputs.exec-cmd }} changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build packages
        run: ${{ steps.pkg-manager.outputs.run-cmd }} ${{ inputs.build-command }}
      - name: Publish prerelease version
        run: ${{ steps.pkg-manager.outputs.exec-cmd }} changeset publish
      - name: Commit
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: "."
          committer_name: bp-deployer
          committer_email: bp-deployer@users.noreply.github.com
          message: "[skip actions] Prerelease ${{inputs.prerelease-tag}}"
