name: "Prerelease Packages"

on:
  workflow_call:
    inputs:
      app-path:
        description: "Specifies a base directory to run the task from"
        required: false
        default: './'
        type: string
      nodejs-version:
        description: "Specifies which Node.js version to use"
        required: false
        default: '16'
        type: string
      package-manager:
        description: "Specifies which package manager to use"
        required: false
        default: ''
        type: string
      build-command:
        description: "Specifies a build command used on package finalizing before publish"
        required: false
        default: 'build'
        type: string
      prerelease-tag:
        description: "Specifies a tag name that is used for prerelease mode"
        required: false
        default: 'pre'
        type: string

env:
  NODE_ENV: production
  CI: true

jobs:
  prerelease:
    name: Run Changesets prerelease
    runs-on: [self-hosted, Linux, X64, cache, node-16]
    defaults:
      run:
        working-directory: ${{ inputs.app-path }}
    steps:
      - name: Use Node.js ${{ inputs.nodejs-version }}
        run: echo ${{ inputs.nodejs-version }} > .nvmrc && nvm use
      - name: Determine which package manager to use
        id: pkg-manager
        uses: bucketplace/ci/.github/actions/select-nodejs-pkg-manager@feature/SC-59
        with:
          package-manager: ${{ inputs.package-manager }}
      - name: Install dependencies
        run: ${{ env.PKG_CMD_INSTALL }}
      - name: Enter prerelease Mode
        run: ${{ env.PKG_CMD_EXEC }} changeset pre enter ${{ inputs.prerelease-tag }}
      - name: Bump version for prerelease
        run: ${{ env.PKG_CMD_EXEC }} changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build packages
        run: ${{ env.PKG_CMD_RUN }} ${{ inputs.build-command }}
      - name: Publish prerelease version
        run: ${{ env.PKG_CMD_EXEC }} changeset publish
      - name: Commit
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: '.'
          committer_name: bp-deployer
          committer_email: bp-deployer@users.noreply.github.com
          message: '[skip actions] Prerelease ${{inputs.prerelease-tag}}'
